### ISSUE TITLE
ScoreInstanceBoost using invalid field

### ISSUE THREAD

**Issue by mish15** [sajari/sajari-sdk-react#41] opened 2016-11-15 23:05 UTC
Should be "minCount", but uses "min_count" and consequently the boost does not work.

**Comment by dhowden** [comment] 2017-04-10 01:15
Looks a lot like #50  @tbillington ?

**Comment by tbillington** [comment] 2017-04-10 02:00
Dupe of https://github.com/sajari/sajari-sdk-react/issues/50.

**Closed by tbillington** 2017-04-10 02:00 UTC
Labels: bug
