### ISSUE TITLE
basic-site-integration: bug with query deletion via typing

### ISSUE THREAD

**Issue by mish15** [sajari/sajari-sdk-react#55] opened 2017-05-28 11:40 UTC
- [ ] If a query is fully selected, then the searcher types (which replaces the entire query), the autocompleted text remains as per previous and javascript errors prevent the search from working. 

- [ ] if a query is deleted via backspace, the autocomplete text remains, even though the query is ""

![screen shot 2017-05-28 at 9 35 13 pm](https://cloud.githubusercontent.com/assets/869412/26528388/21ab5e1e-43ee-11e7-9e8e-f19e77c86e0f.png)
![screen shot 2017-05-28 at 9 29 05 pm](https://cloud.githubusercontent.com/assets/869412/26528389/21affa5a-43ee-11e7-992f-4b5dbab3d3b5.png)

**Comment by tbillington** [comment] 2017-06-06 06:16
Caused by the code that looks for analytics objects on the window incorrectly treating a non-empty `window[""]` value as valid.

https://github.com/sajari/sajari-sdk-react/blob/master/src/ui/Analytics/ga.js#L73

**Comment by tbillington** [comment] 2017-07-28 05:21
This is now fixed. Now check that the value is not an empty string/undefined/null and also points to a function. https://github.com/sajari/sajari-sdk-react/blob/master/src/analytics/ga.js.

**Closed by tbillington** 2017-07-28 05:21 UTC
Labels: bug
